name: cinetopia_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter_modular: ^5.0.3
  flutter_bloc: ^8.1.3
  modular_bloc_bind: ^1.0.1
  equatable: ^2.0.5
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.1.0
  dio: ^5.4.3+1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#15053F"
  image: assets/images/splash.png
  android: true
  ios: true

  android_12:
    image: assets/images/splash.png

flutter:
  uses-material-design: true
